# Generated by Django 3.2.25 on 2026-01-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('new', 'New'), ('refurbished', 'Refurbished')], max_length=20)),
                ('ac_type', models.CharField(choices=[('split', 'Split'), ('window', 'Window')], max_length=20)),
                ('capacity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('energy_rating', models.IntegerField()),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
