# Generated by Django 3.2.25 on 2026-01-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=20)),
                ('profile_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
    ]
