# Generated by Django 3.2.25 on 2026-01-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_maintanence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maintanence',
            new_name='Maintainence',
        ),
    ]
