# Generated by Django 3.2.25 on 2026-01-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_maintanence_maintainence'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainence',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
