# Generated by Django 3.2.25 on 2026-01-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_maintainence_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainence',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
