# Generated by Django 3.2.25 on 2026-01-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
