# Generated by Django 3.2.25 on 2026-01-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_reviews_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='image',
            field=models.ImageField(null=True, upload_to='ac-images/'),
        ),
    ]
