# Generated by Django 3.2.25 on 2026-01-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ac_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='ton',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
