# Generated by Django 3.2.25 on 2026-01-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20260107_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
