# Generated by Django 3.2.25 on 2026-01-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ac_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='is_home_active',
            field=models.BooleanField(default=True),
        ),
    ]
