# Generated by Django 3.2.25 on 2026-01-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_ac_is_home_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='is_home_active',
            field=models.BooleanField(default=False),
        ),
    ]
