# Generated by Django 5.1.3 on 2026-01-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_ac_is_home_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('service_requirements', models.TextField()),
            ],
        ),
    ]
