# Generated by Django 3.2.25 on 2026-01-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_ac_ac_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='ac_type',
            field=models.CharField(choices=[('window', 'Window AC'), ('split', 'Split AC'), ('four_way_cassette', '4 Way Cassette AC'), ('one_way_cassette', 'One Way Cassette AC'), ('tower', 'Tower AC'), ('ductable', 'Ductable AC'), ('hvac', 'HVAC'), ('vrf', 'VRF System'), ('vrv', 'VRV System')], max_length=255),
        ),
    ]
