# Generated by Django 3.2.25 on 2026-01-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_ac_ac_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac',
            name='ac_type',
        ),
        migrations.AddField(
            model_name='ac',
            name='ac_types',
            field=models.CharField(choices=[('window', 'Window AC'), ('split', 'Split AC'), ('four_way_cassette', '4 Way Cassette AC'), ('one_way_cassette', 'One Way Cassette AC'), ('tower', 'Tower AC'), ('ductable', 'Ductable AC'), ('hvac', 'HVAC'), ('vrf', 'VRF System'), ('vrv', 'VRV System')], max_length=255, null=True),
        ),
    ]
