# Generated by Django 3.2.25 on 2026-01-16 20:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20260117_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='ac_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('window', 'Window AC'), ('split', 'Split AC'), ('four_way_cassette', '4 Way Cassette AC'), ('one_way_cassette', 'One Way Cassette AC'), ('tower', 'Tower AC'), ('ductable', 'Ductable AC'), ('hvac', 'HVAC'), ('vrf', 'VRF System'), ('vrv', 'VRV System')], max_length=255, null=True),
        ),
    ]
