# Generated by Django 6.0.1 on 2026-01-18 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_productsell_productsellimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ac-images/')),
                ('ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.ac')),
            ],
        ),
    ]
