# Generated by Django 6.0.1 on 2026-01-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_acimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintainence',
            name='price',
        ),
        migrations.RemoveField(
            model_name='maintainence',
            name='star',
        ),
        migrations.AddField(
            model_name='maintainence',
            name='title',
            field=models.CharField(default='Ac Service', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintainence',
            name='icon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
