"""
Django settings for ac_website project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=oybsf3ns6qnm-ekty7i2ighjl7zvz(j#ihp(mw&u$5jqv%-e5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "cooltechservice.net",
    "www.cooltechservice.net",
    "d2qck9p4j5v4q.cloudfront.net",
    'api.cooltechservice.net',  # <- add this
]

CORS_ALLOWED_ORIGINS = [
    "https://cooltechservice.net",
    "https://www.cooltechservice.net",
     "http://localhost:3000",
]

# Application definition
INSTALLED_APPS = [
    # 'material.admin',  <- REMOVE this line
    # 'unfold',     # optional, or remove if you want default admin
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'django_filters',
    'corsheaders',

    'api',   # your app
]


JAZZMIN_SETTINGS = {

    # -------------------
    # Top Branding
    # -------------------
    "site_title": "CoolTech Admin",
    "site_header": "CoolTech Services",
    "site_brand": "CoolTech Admin ",
    "site_logo": "images/logoo.png",  # put logo in static/images/

    "login_logo": None,
    "login_logo_dark": None,
    "site_icon": None,

    # -------------------
    # Welcome Text
    # -------------------
    "welcome_sign": "Welcome to CoolTech Services",
    "copyright": "CoolTech Services",

    # -------------------
    # Search
    # -------------------
    "search_model": ["auth.User"],

    # -------------------
    # User Avatar
    # -------------------
    "user_avatar": None,

    # -------------------
    # Top Menu Links
    # -------------------
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
    ],

    # -------------------
    # Sidebar
    # -------------------
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # -------------------
    # Icons (FontAwesome)
    # -------------------
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        "home.Property": "fas fa-building",
        "home.Appoinment": "fas fa-calendar-check",
    },

    # -------------------
    # UI Tweaks
    # -------------------
    "related_modal_active": True,
    "custom_css": "css/admin_custom.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
}


JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "",

    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-primary",
    "accent": "accent-flatly",

    "brand_colour": "navbar-success",
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-outline-secondary",
        "success": "btn-success",
        "danger": "btn-danger",
        "warning": "btn-warning",
        "info": "btn-info",
    },
}



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'ac_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ← Add this folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ac_website.wsgi.application'


REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ]
}

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

#DATABASES = {
    #'default': {
   #     'ENGINE': 'django.db.backends.sqlite3',
  #      'NAME': BASE_DIR / 'db.sqlite3',
 #   }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ac_agent',            # Your database name
        'USER': 'ac_user',             # Your MySQL user
        'PASSWORD': 'ac_user@1234',    # Your MySQL password
        'HOST': 'localhost',           # MySQL host
        'PORT': '3306',                # Default MySQL port
        'OPTIONS': {
            'charset': 'utf8mb4',      # Ensure full unicode support
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

SITE_ID = 1

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'rajnepale25@gmail.com'
EMAIL_HOST_PASSWORD = 'vyclullmnpcadgyx'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# URL for static files
STATIC_URL = '/static/'

# Source static files (your app-level or custom static)
STATICFILES_DIRS = [BASE_DIR / 'static']  

# Where collectstatic copies all files for production (Nginx reads this)
STATIC_ROOT = BASE_DIR / 'staticfiles'  

# Media (uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django default primary key type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

